version: '3.0'

services:
  worstbird_postgress_db:
    image: postgres
    environment:
      POSTGRES_DB: "worstbird"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "SuperSecure"
    networks:
      - worstbird_prod
    ports:
      - "5432:5432"
    volumes:
      - pg-data-worstbird:/var/lib/postgresql/data
networks:
    worstbird_prod:
volumes:
    pg-data-worstbird:
