version: '3.0'

services:
  worstbird_web:
      build: 
        context: .
        dockerfile: DockerWeb
      ports: 
        - "8000:8000"
      depends_on:
          - worstbird_db
          # - proxy
          # - letsencrypt
          # - diesel_setup
      container_name: worstbird_web
      networks:
        - worstbird_prod
      volumes:
        - ./www:/www:ro
      environment:
        - VIRTUAL_HOST=yourdomain.toplevel
        - LETSENCRYPT_HOST=yourdomain.toplevel
        - LETSENCRYPT_EMAIL=max.musterman@musterdomain.musterdeutschland
        - ROCKET_DATABASES={pg_worstbird={url="postgres://admin:SuperSecure@worstbird_db:5432/worstbird"}}
        - WAIT_HOSTS=worstbird_db:5432
        - WAIT_HOSTS_TIMEOUT=300
        - WAIT_SLEEP_INTERVAL=30
        - WAIT_HOST_CONNECT_TIMEOUT=30
      command: ./worstbird_http
  worstbird_fetcher:
      build: 
        context: .
        dockerfile: DockerFetcher
      depends_on:
          - worstbird_db
          # - diesel_setup
      container_name: worstbird_fetcher
      networks:
        - worstbird_prod
      environment:
        - DATABASE_URL=postgres://admin:SuperSecure@worstbird_db:5432/worstbird
        - WAIT_HOSTS=worstbird_db:5432
        - WAIT_HOSTS_TIMEOUT=300
        - WAIT_SLEEP_INTERVAL=30
        - WAIT_HOST_CONNECT_TIMEOUT=30
      command: ./worstbird_fetcher
  # diesel_setup:
  #     build:
  #       context: .
  #       dockerfile: DockerDiesel
  #     depends_on:
  #       - worstbird_db
  #     networks:
  #       - worstbird_prod
  #     environment:
  #       - WAIT_HOSTS=worstbird_db:5432
  #       - WAIT_HOSTS_TIMEOUT=300
  #       - WAIT_SLEEP_INTERVAL=30
  #       - WAIT_HOST_CONNECT_TIMEOUT=30
  #     command: sh -c "/wait && diesel database setup && diesel migration run"


  worstbird_db:
    image: postgres
    container_name: worstbird_db
    environment:
      POSTGRES_DB: "worstbird"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "SuperSecure"
    networks:
      - worstbird_prod
    ports:
      - "5432:5432"
    volumes:
      - pg-data-worstbird:/var/lib/postgresql/data
networks:
    worstbird_prod:
volumes:
    pg-data-worstbird:
